### ISSUE TITLE
Does the CDNS support the local to local visit?

### ISSUE THREAD

**Issue by lancasterJie** [Polidea/Cellular-Data-Network-Simulator#12]
Hi guys

I'm trying to use the smartphone to visit the local web server, and I have installed the 
CDNS on my router successfully, and select the GPRS or other options. 
It works well when the smartphone try to connect the outside internet websites(LAN to WAN).
But the CDNS seems did not work for the local network conncetions(LAN to LAN), when the 
smartphone tried to connect the local web serve., When i choose the Disable option, the smartphone
get the local websites still. So, does the CDNS not support the local to local visit, right?
Apologize for my poor English writing.

Best Regards

Jie

**Comment by ayufan** [comment]
The web server has to be routed, because the traffic then goes over LAN/Switch and is not being shaped by CDNS. CDNS work on lan-to-wan as there's no easy way to limit lan-to-lan speed.

**Comment by lancasterJie** [comment]
Ok. Thanks for your reply
